### ISSUE TITLE
Convertir a HTML

### ISSUE THREAD

**Issue by crguezl** [marreA/MPP_TFM#1]
Es una sugerencia.

Estaría estupendo si conviertes la memo a HTML dejando los *.html en `docs` y activas las GH-pages con la opción `docs` folder. De esta forma tendríamos la memoria navegable en el site asociado al repo.

* [LaTeX/Export To Other Formats](https://en.wikibooks.org/wiki/LaTeX/Export_To_Other_Formats#Convert_to_HTML)

**Comment by amarrerod** [comment]
Muchas gracias por la sugerencia!. Acabo de aceptar el pull-request y el enlace esta en la sección de código.
La verdad es que queda bastante bien.
